spring:
  application:
    name: newApp
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: ahmed
    password: ahmed
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
server:
  port: 8090


