spring:
  application:
    name: newApp
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: ahmed
    password: ahmed
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
server:
  port: 8090


